---
- name: Reboot
  shell: nohup bash -c "sleep 2; reboot" &

- name: Wait for shutdown
  local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 timeout=60 state=stopped
  sudo: no

- name: Wait for boot
  local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 delay=10 timeout=60 state=started
  sudo: no